language: c
sudo: required

env:
  global:
        - COVERITY_SCAN_BRANCH_PATTERN="(master|coverity-.*)"
        - COVERITY_SCAN_NOTIFICATION_EMAIL="dev@umlaeute.mur.at"
        - COVERITY_SCAN_BUILD_COMMAND="make"

matrix:
  include:
    - compiler: clang
    - compiler: gcc
      env:
        - COVERITY_SCAN_PROJECT_NAME="$TRAVIS_REPO_SLUG"

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq puredata-dev

before_script:
  # implement Coverity Scan with before_script instead of addons.coverity_scan
  # to work around too-early quota check by the coverity_scan addon
  - if [[ -n $COVERITY_SCAN_PROJECT_NAME ]] ; then curl -s 'https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh' | bash || true ; fi

script:
- make
